mysite/aquariums/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views
from django.conf.urls import handler403

handler403 = 'aquariums.views.permission_denied'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<aquarium_id>[0-9]+)', views.detail, name='detail'),
    url(r'^fishtypes', views.fishtypes),
    url(r'logout', 'django.contrib.auth.views.logout',
                          {'next_page': '/accounts/login/'}),
    url(r'runlife', views.run_iteration),
    url(r'addfish', views.add_fish),
    url(r'movefish', views.move_fish),
    url(r'addaquarium', views.add_aquarium),
    url(r'editaquarium/(?P<aquarium_id>[0-9]+)/save', views.edit_aquarium_save),
    url(r'editaquarium/(?P<aquarium_id>[0-9]+)', views.edit_aquarium),
    url(r'^deleteaquarium', views.delete_aquarium),
    url(r'^deletefish', views.delete_fish),
    url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

handler403 = 'aquariums.views.permission_denied'

urlpatterns = [
    url(r'^accounts/login/$', auth_views.login),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^aquariums/', include('aquariums.urls')),
    url(r'^admin/', admin.site.urls),
    url('', include('aquariums.urls'))
]

mysite/aquariums/models.py
from random import Random

from django.contrib.auth.models import User
from django.db import models
from django.db.models import F


class Aquarium(models.Model):
    name = models.CharField(max_length=200)
    water_amount = models.IntegerField(default=0)
    user = models.ForeignKey(User, default=None)
    iteration = models.IntegerField(default=0)



    def __str__(self):
        return self.name + ' (' + str(self.water_amount) + ' liters )'

    def _filled_percent(self):
        fishes = Fish.objects.filter(aquarium=self)
        used = 0.0
        for fish in fishes:
            used += fish.fish_type.water_amount
        return used/float(self.water_amount)

    filled_percent = property(_filled_percent)


class FishType(models.Model):
    name = models.CharField(max_length=200)
    max_lifetime = models.IntegerField(default=0)
    water_amount = models.FloatField(default=1.0)
    fry_period = models.IntegerField(default=0)
    spawning_period = models.IntegerField(default=0)
    max_fries_count = models.IntegerField(default=0)
    males_percent = models.FloatField(default=0.5)
    fry_die_period = models.IntegerField(default=0)
    fry_deaths_percent = models.FloatField(default=0.0)
    image_url = models.CharField(max_length=1000, default="")

    def __str__(self):
        return self.name


class Fish(models.Model):
    MALE = 0
    FEMALE = 1
    random = Random()


    fish_type = models.ForeignKey(FishType)
    age = models.IntegerField(default=0)
    lifetime = models.IntegerField(default=0)
    gender = models.IntegerField(default=0, choices=((MALE, 'MALE'), (FEMALE, 'FEMALE')))
    aquarium = models.ForeignKey(Aquarium, default=None)

    def __str__(self):
        return str(self.fish_type) + '_' + str(self.id)

    def is_alife(self):
        return self.age < self.lifetime

    def set_lifetime(self):
        type = self.fish_type
        if self.age < type.fry_die_period:
            self.lifetime = Fish.random.randint(0, type.fry_die_period)
            survived_fry = type.fry_deaths_percent*100 > Fish.random.randint(0, 100)
            if survived_fry:
                 self.lifetime = Fish.random.randint(type.fry_die_period, type.max_lifetime)
        else:
            self.lifetime = Fish.random.randint(self.age, type.max_lifetime)

    def spawn(self):
        if self.gender == Fish.MALE \
            or self.age <= self.fish_type.fry_period \
            or self.age % self.fish_type.spawning_period != 0:
            return
        count = Fish.random.randint(0, self.fish_type.max_fries_count)
        for i in range(0, count):
            gender = Fish.FEMALE if Random().random() >= self.fish_type.males_percent else Fish.MALE
            fish = Fish.objects.create(fish_type=self.fish_type, age=0, lifetime = 0,
                        gender = gender, aquarium=self.aquarium)
            fish.set_lifetime()
            fish.save()

    @staticmethod
    def total_count(aquarium=None, type=None):
        query = Fish.objects
        if aquarium:
            query = query.filter(aquarium=aquarium)
        if type:
            query = query.filter(fish_type = type)
        return query.count()

    @staticmethod
    def females_count(aquarium=None, type=None):
        query = Fish.objects
        if aquarium:
            query = query.filter(aquarium=aquarium)
        if type:
            query = query.filter(fish_type = type)

        return query.filter(gender=Fish.FEMALE).filter(age__gte=F("fish_type__fry_period")).count()

    @staticmethod
    def fries_count(aquarium=None, type=None):
        query = Fish.objects
        if aquarium:
            query=query.filter(aquarium=aquarium)

        if type:
            query = query.filter(fish_type = type)

        return query.filter(age__lt=F("fish_type__fry_period")).count()

mysite/aquariums/forms.py
from django import forms

from .models import Fish, FishType, Aquarium


# class DeleteAquariumForm(forms.Form):
#     aquarium_id = forms.IntegerField(label='Your name', max_length=100)

class AddFishForm(forms.ModelForm):
    fish_type = forms.ModelChoiceField(queryset=FishType.objects.all(), empty_label=None)
    class Meta:
        model=Fish
        fields = ["fish_type", "age", "gender"]

class AddAquariumForm(forms.ModelForm):
    class Meta:
        model=Aquarium
        fields = ["name", "water_amount"]

mysite/aquariums/views.py
from django.contrib.auth.decorators import login_required
from django.forms import model_to_dict
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.template import RequestContext, loader

from .forms import AddFishForm, AddAquariumForm
from .models import Aquarium, Fish, FishType


@login_required
def index(request):
    aquarium_list = Aquarium.objects.order_by('-name').filter(user=request.user)
    context = {'aquarium_list': aquarium_list, "add_aquarium_form": AddAquariumForm()}

    return render(request, "aquariums/index.html", context)


@login_required
def detail(request, aquarium_id):
    aquarium = get_object_or_404(Aquarium, pk=aquarium_id)

    if aquarium.user != request.user:
        return HttpResponseForbidden(loader.render_to_string("403.html"))

    aquarium_list = Aquarium.objects.filter(user=request.user).exclude(id=aquarium.id)

    fishes = Fish.objects.filter(aquarium=aquarium).order_by('-age', 'id')
    statistics = {"total": str(Fish.total_count(aquarium)), "females": str(Fish.females_count(aquarium)),
                  "fries": str(Fish.fries_count(aquarium))}
    fishtypes = FishType.objects.all()
    stat_array = []
    for type in fishtypes:
        typestat = {}
        typestat["name"] = type.name
        typestat["total"] = str(Fish.total_count(aquarium, type))
        typestat["females"] = str(Fish.females_count(aquarium, type))
        typestat["fries"] = str(Fish.fries_count(aquarium, type))
        stat_array.append(typestat)

    statistics["types"] = stat_array
    return render(request, 'aquariums/detail.html', {'aquarium': aquarium, 'fishes': fishes,
                                                     'aquariums_list': aquarium_list, "add_fish_form": AddFishForm(), "statistics": statistics})

@login_required
def fishtypes(request):
    fishtypes = FishType.objects.all()
    stat_array = []
    for type in fishtypes:
        typestat = {}
        typestat["name"] = type.name
        typestat["total"] = str(Fish.total_count(type=type))
        typestat["females"] = str(Fish.females_count(type=type))
        typestat["fries"] = str(Fish.fries_count(type=type))
        stat_array.append(typestat)

    return render(request, 'aquariums/fishtypes.html', {"fishtypes_stat": zip(fishtypes, stat_array), "typestatistics": stat_array})


def permission_denied(request):
    response = render_to_response(
        '403.html',
        context_instance=RequestContext(request)
    )

    response.status_code = 403

    return response

@login_required
def delete_aquarium(request):
    id = request.POST['aquarium_id']
    aquarium = get_object_or_404(Aquarium, pk=id)

    if aquarium.user != request.user:
        return HttpResponseForbidden(loader.render_to_string("403.html"))

    aquarium.delete()
    return index(request)

@login_required
def delete_fish(request):
    id = request.POST['fish_id']
    fish = get_object_or_404(Fish, pk=id)
    aquarium_id = fish.aquarium.id

    if fish.aquarium.user != request.user:
        return HttpResponseForbidden(loader.render_to_string("403.html"))

    fish.delete()
    return redirect("aquariums/" + str(aquarium_id)+"/")

@login_required
def move_fish(request):
    id = request.POST['fish_id']
    fish = get_object_or_404(Fish, pk=id)
    old_aquarium = fish.aquarium

    if not 'new_aquarium_id' in request.POST.keys():
        return redirect("aquariums/"+str(old_aquarium.id)+"/")

    new_aq_id = request.POST['new_aquarium_id']
    new_aquarium = get_object_or_404(Aquarium, pk=new_aq_id)

    if fish.aquarium.user != request.user or new_aquarium.user != request.user:
        return HttpResponseForbidden(loader.render_to_string("403.html"))

    fish.aquarium = new_aquarium
    fish.save()

    return redirect("aquariums/"+str(old_aquarium.id)+"/")

@login_required
def add_fish(request):
    fish = AddFishForm(request.POST).save(commit=False)
    aquarium_id = request.POST["aquarium"]
    aquarium = get_object_or_404(Aquarium, id=aquarium_id)
    fish.aquarium = aquarium
    fish.set_lifetime()
    fish.save()
    # data = serializers.serialize('json', [fish,])
    # struct = json.loads(data)
    # data = json.dumps(struct[0])
    redir = "aquariums/"+str(aquarium.id)+"/"
    return redirect(redir)
    # return HttpResponse(data, content_type='application/json')

@login_required
def add_aquarium(request):
    aquarium = AddAquariumForm(request.POST).save(commit=False)
    aquarium.user = request.user
    aquarium.save()
    return redirect("aquariums/")

@login_required
def run_iteration(request):
    aquarium_id = request.POST["aquarium_id"]
    aquarium = get_object_or_404(Aquarium, id=aquarium_id)
    iterations = int(request.POST["iterations"])
    for i in range(iterations):
        update_aquarium(aquarium)

    aquarium.iteration += iterations
    aquarium.save()
    return redirect("/aquariums")

def update_aquarium(aquarium):
    fishes = Fish.objects.filter(aquarium=aquarium)
    for fish in fishes:
        if not fish.is_alife():
            fish.delete()
        else:
            fish.age += 1
            fish.spawn()
            fish.save()

@login_required
def edit_aquarium(request, aquarium_id):
    aquarium = get_object_or_404(Aquarium, id=aquarium_id)
    if aquarium.user != request.user:
        return HttpResponseForbidden(loader.render_to_string("403.html"))

    context = {"edit_aquarium_form": AddAquariumForm(instance=aquarium), "aquarium":aquarium}
    return render(request, "aquariums/edit_aquarium.html", context)

@login_required
def edit_aquarium_save(request, aquarium_id):
    aquarium = get_object_or_404(Aquarium, id=aquarium_id)
    clean = "clean" in request.POST.keys()

    aquarium = AddAquariumForm(request.POST, instance=aquarium).save(commit=(not clean))
    if aquarium.user != request.user:
        return HttpResponseForbidden(loader.render_to_string("403.html"))
    if clean:
        aquarium.iteration = 0
        Fish.objects.filter(aquarium=aquarium).delete()
        aquarium.save()
    return redirect("/aquariums")

mysite/aquariums/templates/aquariums/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'aquariums/style.css' %}"/>

<head>
    <meta charset="UTF-8">
    <title>Aquariums</title>
    <link rel="shortcut icon" href="{% static 'aquariums/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'aquariums/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'aquariums/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'aquariums/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'aquariums/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'aquariums/manifest.json' %}">
    <!--<script type="text/javascript" src="{% static 'aquariums/jquery-1.12.3.min.js' %}"></script>-->
</head>

<body>
<header>
    <a href="/aquariums/" class="nav-link"><h1> Aquariums </h1></a>
</header>

<nav>
    {% if not user.is_anonymous %}
    <table class="nav-table">
        <tr>
            <td><a href="/aquariums/" class="nav-link"> Aquariums </a></td>
            <td><a href="/fishtypes" class="nav-link"> Fish types </a></td>
            <td><a href="/logout/" class="nav-link"> [ {{ user }} ] logout </a></td>
        </tr>
    </table>
    {% endif %}
</nav>

<section class="content">
    {% block content %}
    {% endblock %}
</section>

<section class="content menu">
    {% block menu %}
    {% endblock %}
</section>

</body>

</html>

mysite/aquariums/templates/aquariums/detail.html
{% extends 'aquariums/base.html' %}
{% load staticfiles%}

{% block content %}
<div class="stat-table">
    <div class="stat-column">
        <table>
            <tbody>
                <tr class="row1">
                    <th> Aquarium name: </th>
                    <td> {{aquarium.name}}</td>
                </tr>
                <tr class="row2">
                    <th> Water amount: </th>
                    <td> {{aquarium.water_amount}}</td>
                </tr>
                <tr class="row1">
                    <th> Fishes count: </th>
                    <td> {{statistics.total}}</td>
                </tr>
                <tr class="row2">
                    <th> Females count: </th>
                    <td> {{statistics.females}}</td>
                </tr>
                <tr class="row1">
                    <th> Fries count: </th>
                    <td> {{statistics.fries}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% for typestat in statistics.types %}
        <div class="stat-column">
            <table>
            <tbody>
                <tr class="row1">
                    <th> Type name: </th>
                    <td> {{typestat.name}}</td>
                </tr>
                <tr></tr>

                <tr class="row1">
                    <th> Fishes count: </th>
                    <td> {{typestat.total}}</td>
                </tr>
                <tr class="row2">
                    <th> Females count: </th>
                    <td> {{typestat.females}}</td>
                </tr>
                <tr class="row1">
                    <th> Fries count: </th>
                    <td> {{typestat.fries}}</td>
                </tr>
            </tbody>
        </table>
        </div>
    {% endfor %}
</div>


    <table>
        <thead>
            <tr>
                <th> Fish id </th>
                <th> Fish type </th>
                <th> Age (months)</th>
                <th> Gender </th>
                <th> Move fish </th>
                <th> Remove fish</th>
            </tr>
        </thead>
        <tbody>
            {% for fish in fishes %}
                <tr class="{% cycle 'row1' 'row2' %}">
                    <td> {{fish.id}}</td>
                    <td> <p class="tooltip">
                         {{fish.fish_type}}
                        <span>
                            <img class="callout fishtype_img" src="{{fish.fish_type.image_url}}" align="middle" /><br/>
                            <strong>{{fish.fish_type}}</strong><br/>
                            Max lifetime: {{fish.fish_type.max_lifetime}} months<br/>
                            Required water amount: {{fish.fish_type.water_amount}} liters<br/>
                            Males: {% widthratio fish.fish_type.males_percent 1 100 %}% <br/>
                            Spawning period: {{fish.fish_type.spawning_period}} months <br/>
                            Max fries count: {{fish.fish_type.max_fries_count}} <br/>
                            Is fry until: {{fish.fish_type.fry_period}} months<br/>
                            Fry's high mortality period: {{fish.fish_type.fry_die_period}} months<br/>
                            Deaths on high mortality period: {% widthratio fish.fish_type.fry_deaths_percent 1 100 %}%<br/>
                        </span>
                    </p>
                    </td>
                    <td> {{fish.age}}</td>
                    <td> {{fish.get_gender_display}}</td>
                    <td>
                    <form action="/movefish" method="post">
                            {% csrf_token %}
                            <select name="new_aquarium_id" >
                                {% for aquarium in aquariums_list%}
                                    <option value="{{aquarium.id}}">{{aquarium}}</option>
                                {% endfor %}
                            </select>
                            <input type="hidden" name="fish_id" value="{{fish.id}}"/>
                            <input type="image" class="run_img" src="{% static 'aquariums/move.png' %}" width="25em" height="25em"/>
                        </form>
                    </td>
                    <td>
                        <form action="/deletefish" method="post" onsubmit="return confirm('Do you really want to remove the {{fish.fish_type}} with id {{fish.id}}?');">
                            {% csrf_token %}
                            <input type="hidden" name="fish_id" value="{{fish.id}}"/>
                            <input type="image" src="{% static 'aquariums/delete.png' %}" width="25em" height="25em"/>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block menu %}


<script>
    function check(){
        age = document.getElementById("id_age");
        if(age.value < 0){
            alert("Age must be 0 or greater.");
            age.value = 0;
            return false;
        }
        return true;
    }
</script>
<form action="/addfish" method="post" onsubmit="return check()">
    {% csrf_token %}
    <table>
        {{add_fish_form.as_table}}
    </table>
    <input type="hidden" name="aquarium" value="{{aquarium.id}}"/>
    <input type="submit" value="Add fish"/>
</form>

<!--<script>
function addfish(){
    $.ajax({
        url:'addfish',
        type:'post',
        data:$('#addfish_form').serialize(),
        success:function(){
            console.log("success");
        },
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};
</script>-->
{% endblock %}

mysite/aquariums/templates/aquariums/edit_aquarium.html
{% extends 'aquariums/base.html' %}
{% load staticfiles%}

{% block content %}
<form action="/editaquarium/{{aquarium.id}}/save" method="post" >
    {% csrf_token %}
    <table>
        {{edit_aquarium_form.as_table}}
    </table>
    <label class="checkbox">
        <input type="checkbox" name="clean" id="clean"/>
        <span></span>
        <label>Clean aquarium</label>
    </label>
    <input type="submit" value="Edit" id="edit-aquarium-button"/>
</form>
{% endblock %}

mysite/aquariums/templates/aquariums/fishtypes.html
{% extends 'aquariums/base.html' %}
{% load staticfiles%}

{% block content %}
<div class="stat-table">
    {% for fishtype, typestat in fishtypes_stat%}
    <div class="stat-column">
        <table>
            <tbody>
            <tr>
                <td colspan="2"><img src="{{fishtype.image_url}}" height="100em"/></td>
            </tr>
            <tr class="row1">
                <th> Type name:</th>
                <td> {{typestat.name}}</td>
            </tr>
            <tr></tr>
            <tr class="row2">
                <th> Max lifetime:</th>
                <td>{{fishtype.max_lifetime}} months</td>
            </tr>
            <tr class="row1">
                <th>Required water amount:</th>
                <td>{{fishtype.water_amount}} liters</td>
            </tr>
            <tr class="row2">
                <th>Males:</th>
                <td>{% widthratio fishtype.males_percent 1 100 %}%</td>
            </tr>
            <tr class="row1">
                <th>Spawning period:</th>
                <td>{{fishtype.spawning_period}} months</td>
            </tr>
            <tr class="row2">
                <th>Max fries count:</th>
                <td>{{fishtype.max_fries_count}}</td>
            </tr>
            <tr class="row1">
                <th>Is fry until:</th>
                <td>{{fishtype.fry_period}} months</td>
            </tr>
            <tr class="row2">
                <th>Fry's high mortality period:</th>
                <td>{{fishtype.fry_die_period}} months</td>
            </tr>
            <tr class="row1">
                <th>Deaths on high mortality period:</th>
                <td>{% widthratio fishtype.fry_deaths_percent 1 100 %}%</td>
            </tr>
            <tr></tr>
            <tr class="row2">
                <th> Fishes count:</th>
                <td> {{typestat.total}}</td>
            </tr>
            <tr class="row1">
                <th> Females count:</th>
                <td> {{typestat.females}}</td>
            </tr>
            <tr class="row2">
                <th> Fries count:</th>
                <td> {{typestat.fries}}</td>
            </tr>
            </tbody>
        </table>
    </div>

    {% endfor %}
</div>
{% for typestat in typestatistics %}

{% endfor %}
{% endblock %}

mysite/aquariums/templates/aquariums/index.html
{% extends 'aquariums/base.html' %}
{% load staticfiles%}

{% block content %}

    {% if aquarium_list %}
        <table>
        <thead>
            <tr>
                <th> Name </th>
                <th> Water amount </th>
                <th> Filled percentage </th>
                <th> Iteration </th>
                <th> Run months </th>
                <th> Edit </th>
                <th> Delete </th>
            </tr>
        </thead>
        <tbody>
            {% for aquarium in aquarium_list %}
                <tr class="{% cycle 'row1' 'row2' %}">
                    <td> <a href="/aquariums/{{ aquarium.id }}/">{{ aquarium.name }}</a></td>
                    <td> {{aquarium.water_amount}} liters</td>
                    <td> {{aquarium.filled_percent}}</td>
                    <td> {{aquarium.iteration}}</td>
                    <td>
                        <form action="/runlife" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="aquarium_id" value="{{aquarium.id}}"/>
                            <input type="number" name="iterations" value="1" min="1" max="100" height="25em"/>
                            <input type="image" class="run_img" src="{% static 'aquariums/play.png' %}"
                                   width="25em" height="25em" value="{{aquarium.id}}"/>
                        </form>
                    </td>
                    <td> <a href="/editaquarium/{{aquarium.id}}">
                        <img src="{% static 'aquariums/edit.png' %}" width="25em" height="25em"/>
                        </a>
                    </td>
                    <td> <form action="/deleteaquarium" method="post" onsubmit="return confirm('Do you really want to delete the {{aquarium.name}}?');">
                        {% csrf_token %}
                        <input type="hidden" name="aquarium_id" value="{{aquarium.id}}"/>
                        <input type="image" src="{% static 'aquariums/delete.png' %}"
                               width="25em" height="25em" />
                    </form></td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
    {% else %}
        <p>No aquariums are available.</p>
    {% endif %}
{% endblock %}
{% block menu %}
<script>
    function check(){
        var valid = document.getElementById("id_name").value != "" &&
                document.getElementById("id_water_amount").value > 0;
        if(!valid){
            alert("Fields are not filled correctly.")
        }
        return valid;
    }
</script>
<form action="/addaquarium" method="post" onsubmit="return check()" >
    {% csrf_token %}
    <table>
        {{add_aquarium_form.as_p}}
    </table>
    <input type="submit" value="Add aquarium" />
</form>
{% endblock%}